#!/usr/bin/env bash
# Install HAproxy on lb-01 server

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 270804-web-01 100.24.244.249 check
    server 270804-web-02 100.25.155.110 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
